# POSTGRES CONFIG
# gcloud compute disks create --size 200GB postgres-disk
apiVersion: v1
kind: ConfigMap
metadata:
  name: explorer-config
data:
  VUE_APP_WSS_ENDPOINT: 'ws://0.0.0.0:6006'
---
apiVersion: v1
kind: Service
metadata:
  name: explorer
  labels:
    app: explorer-deployment
    tier: rippled
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: explorer-deployment
    tier: rippled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: explorer-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
        app: explorer-deployment
        tier: rippled
  template:
    metadata:
      labels:
        app: explorer-deployment
        tier: rippled
    spec:
      containers:
      - name: explorer-deployment
        image: gcr.io/metaxrplorer/explorer:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: explorer-config