# docker compose -f docker-compose.yml up --build --force-recreate -d
version: '3.4'
services:
  node1:
    build:
      context: node1
      dockerfile: Dockerfile
    container_name: node1-chain
    ports:
      - "6006:6006"
      - "30311:30311"
    networks:
      - rippled
    volumes:
      # - ./node1/keystore:/var/lib/rippled/keystore
      - ./node1/db:/var/lib/rippled/db
  node2:
    build:
      context: node2
      dockerfile: Dockerfile
    container_name: node2-chain
    ports:
      - "6008:6008"
      - "30312:30312"
    volumes:
      # - ./node2/keystore:/var/lib/rippled/keystore
      - ./node2/db:/var/lib/rippled/db
    networks:
      - rippled
networks:
  rippled:
    driver: bridge