#!/bin/bash

self(){
  DIR=$( cd "$( dirname "$0" )/" && pwd)
  echo $DIR
}

$(self)/down

PORT=80

CUSTOMPORT=$(echo $1|egrep "^[0-9]+$"|wc -l)

if [[ "$CUSTOMPORT" -gt "0" ]]; then
    PORT=$1
fi

docker run \
    -dit \
    --name xrpld \
    -p $PORT:6005 \
    -v $(self)/../config:/config/ \
    $1/$2:latest

docker logs -f xrpld
