version: '3.4'
services:
  witness:
    build:
      context: ./xchains/comms
      dockerfile: Dockerfile
    container_name: rippled-witness1
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # - ./xchains/comms/config:/app/config
      - ./rippled-xchain-latest/rippled:/app/rippled
      - ./witness-latest/witness:/app/witness
    command: >
      poerty shell ./scripts/tutorial.sh