# gcloud builds submit --config cloudbuild.boost.yaml --region=us-central1
# NOTE: This is triggered for each pr to boost.
steps:
  # BUILD boost
  # Pull the latest image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        docker pull gcr.io/$PROJECT_ID/boost:$_BOOST_VERSION || exit 0
  # Build & Tag the 
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'gcr.io/$PROJECT_ID/boost:$_BOOST_VERSION',
      '-f', 'boost.dockerfile',
      '.',
      '--build-arg', 'BOOST_DIR=$_BOOST_DIR',
      '--build-arg', 'BOOST_VERSION=$_BOOST_VERSION',
      '--cache-from', 'gcr.io/$PROJECT_ID/boost:$_BOOST_VERSION'
    ]
    dir: 'builder/docker'
  # Push the image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/boost:$_BOOST_VERSION']
images:
  - 'gcr.io/$PROJECT_ID/boost:$_BOOST_VERSION'
serviceAccount: 'projects/$PROJECT_ID/serviceAccounts/$PROJECT_ID@appspot.gserviceaccount.com'
options:
  substitutionOption: ALLOW_LOOSE
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/rippled'
timeout: 1500s